// PixInsight JavaScript Runtime stub
// ----------------------------------------------------------------------------
// LinearPatternSubtraction.js - Released 9/25/2023 1:51:58 PM
// ----------------------------------------------------------------------------
// This is a stub file, to be used as a development aid in developing
// JavaScript-based PixInsight plugins.
//
// Copyright (c) 2023 Gregorius S. Soedharmo (aka Arkatufus).
// ----------------------------------------------------------------------------
//
//     ____       __ _____  ____
//    / __ \     / // ___/ / __ \
//   / /_/ /__  / / \__ \ / /_/ /
//  / ____// /_/ / ___/ // _, _/   PixInsight JavaScript Runtime
// /_/     \____/ /____//_/ |_|    PJSR Version 1.0
// ----------------------------------------------------------------------------
// pjsr/LinearPatternSubtraction.jsh - Released 2023-08-28T15:24:27Z
// ----------------------------------------------------------------------------
// This file is part of the PixInsight JavaScript Runtime (PJSR).
// PJSR is an ECMA-262-5 compliant framework for development of scripts on the
// PixInsight platform.
//
// Copyright (c) 2003-2023 Pleiades Astrophoto S.L. All Rights Reserved.
//
// Redistribution and use in both source and binary forms, with or without
// modification, is permitted provided that the following conditions are met:
//
// 1. All redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//
// 2. All redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the names "PixInsight" and "Pleiades Astrophoto", nor the names
//    of their contributors, may be used to endorse or promote products derived
//    from this software without specific prior written permission. For written
//    permission, please contact info@pixinsight.com.
//
// 4. All products derived from this software, in any form whatsoever, must
//    reproduce the following acknowledgment in the end-user documentation
//    and/or other materials provided with the product:
//
//    "This product is based on software from the PixInsight project, developed
//    by Pleiades Astrophoto and its contributors (https://pixinsight.com/)."
//
//    Alternatively, if that is where third-party acknowledgments normally
//    appear, this acknowledgment must be reproduced in the product itself.
//
// THIS SOFTWARE IS PROVIDED BY PLEIADES ASTROPHOTO AND ITS CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL PLEIADES ASTROPHOTO OR ITS
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, BUSINESS
// INTERRUPTION; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; AND LOSS OF USE,
// DATA OR PROFITS) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
// ----------------------------------------------------------------------------

const LPS_DEFAULT_INPUT_FILES = [];
const LPS_DEFAULT_TARGET_IS_ACTIVE_IMAGE = false;
const LPS_DEFAULT_CLOSE_FORMER_WORKING_IMAGES = false;
const LPS_DEFAULT_OUTPUT_DIR = "";
const LPS_DEFAULT_CORRECT_COLUMNS = true;
const LPS_DEFAULT_CORRECT_ENTIRE_IMAGE = false;
const LPS_DEFAULT_DEFECT_TABLE_FILE_PATH = "";
const LPS_DEFAULT_POSTFIX = "_lps";
const LPS_DEFAULT_LAYERS_TO_REMOVE = 9;
const LPS_DEFAULT_REJECTION_LIMIT = 3;
const LPS_DEFAULT_GLOBAL_REJECTION = true;
const LPS_DEFAULT_GLOBAL_REJECTION_LIMIT = 5;
const LPS_DEFAULT_BACKGROUND_REFERENCE_LEFT = 0;
const LPS_DEFAULT_BACKGROUND_REFERENCE_TOP = 0;
const LPS_DEFAULT_BACKGROUND_REFERENCE_WIDTH = 512;
const LPS_DEFAULT_BACKGROUND_REFERENCE_HEIGHT = 512;
const LPS_DEFAULT_DEFECT_COLUMN_ROW = undefined;
const LPS_DEFAULT_DEFECT_START_PIXEL = undefined;
const LPS_DEFAULT_DEFECT_END_PIXEL = undefined;
/*
 * LinearPatternSubtraction
 *
 * Corrects residual column or row patterns in a list of images.
 *
 * This procedure reuses some code written by Georg Viehoever in the
 * CanonBandingReduction script and applies the column or row correction in the
 * multiscale context. The engine also includes outlier rejection for a more
 * robust statistical evaluation.
 *
 * The procedure corrects entire rows or columns, but it can also correct
 * partial rows or columns by reading a defect table generated by
 * CosmeticCorrection. Thus, if you want to correct partial rows or columns,
 * you should first run CosmeticCorrection, manually create the defect list,
 * and save it to a text file.
 */
class LPSEngine
{
    constructor() { };
   // set defaults
    inputFiles = LPS_DEFAULT_INPUT_FILES;
    targetIsActiveImage = LPS_DEFAULT_TARGET_IS_ACTIVE_IMAGE;
    closeFormerWorkingImages = LPS_DEFAULT_CLOSE_FORMER_WORKING_IMAGES;
    outputDir = LPS_DEFAULT_OUTPUT_DIR;
    correctColumns = LPS_DEFAULT_CORRECT_COLUMNS;
    correctEntireImage = LPS_DEFAULT_CORRECT_ENTIRE_IMAGE;
    defectTableFilePath = LPS_DEFAULT_DEFECT_TABLE_FILE_PATH;
    postfix = LPS_DEFAULT_POSTFIX;
    layersToRemove = LPS_DEFAULT_LAYERS_TO_REMOVE;
    rejectionLimit = LPS_DEFAULT_REJECTION_LIMIT;
    globalRejection = LPS_DEFAULT_GLOBAL_REJECTION;
    globalRejectionLimit = LPS_DEFAULT_GLOBAL_REJECTION_LIMIT;
    backgroundReferenceLeft = LPS_DEFAULT_BACKGROUND_REFERENCE_LEFT;
    backgroundReferenceTop = LPS_DEFAULT_BACKGROUND_REFERENCE_TOP;
    backgroundReferenceWidth = LPS_DEFAULT_BACKGROUND_REFERENCE_WIDTH;
    backgroundReferenceHeight = LPS_DEFAULT_BACKGROUND_REFERENCE_HEIGHT;
    defectColumnOrRow = LPS_DEFAULT_DEFECT_COLUMN_ROW;
    defectStartPixel = LPS_DEFAULT_DEFECT_START_PIXEL;
    defectEndPixel = LPS_DEFAULT_DEFECT_END_PIXEL;
}


// ----------------------------------------------------------------------------
// EOF pjsr/LinearPatternSubtraction.jsh - Released 2023-08-28T15:24:27Z


